name = 'smolstar'
license = 'MIT'
licenselink = 'https://github.com/brunoarine/smolstar/LICENSE'
description = 'A Hugo theme for the smolweb'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/brunoarine/smolstar'

# If you have a running demo of the theme
demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['blog', 'smolweb', 'minimalist']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Bruno Arine'
  homepage = 'https://www.brunoarine.com'

